language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gkreiken/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gkreiken/udemy-docker-react npm run test